version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nikki_db
    ports:
      - "3306:3306"
    volumes:
      - rails-db:/var/lib/mysql 
    tty: true  ## tty: trueを追加
 
  web: &web
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    stdin_open: true
    tty: true
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - db
 
  webpacker:
    <<: *web
    command: bundle exec bin/webpack-dev-server
    depends_on: []
    environment:
      WEBPACKER_DEV_SERVER_HMR: "true"
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"
    volumes:
      - .:/myapp
volumes:
  rails-db: